package enums

const (
	USER_ACCOUNT_STATUS_NOT_ACTIVE string = "NOT_ACTIVE"
	USER_ACCOUNT_STATUS_ACTIVE     string = "ACTIVE"
	USER_ACCOUNT_STATUS_BANNED     string = "BANNED"

	USER_GENDER_MALE   string = "MALE"
	USER_GENDER_FEMALE string = "FEMALE"
	USER_GENDER_OTHER  string = "OTHER"

	USER_VERIFICATION_STATUS_NOT_VERIFIED string = "NOT_VERIFIED"
	USER_VERIFICATION_STATUS_VERIFIED     string = "VERIFIED"
)
